server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-0.eureka:8500/eureka/,http://eureka-1.eureka:8500/eureka/,http://eureka-2.eureka:8500/eureka/

  instance:
    prefer-ip-address: true

ithinkdt:
  security:
    social:
      - icon: wechat.png
        icon_alive: alive-wechat.png
        title: 敏桥SSO登录
        auth_type: Author2.0
        auth_kind: agilinesSso
        client_id: pcp
        client_secret: 123456
        url: '[HOST]/api/v1/gateway/sso/ssologin/callback'
        user-authorization-uri: https://sso-upower.agilines.com/pub/oauth2/authorize?response_type=code&client_id=[CLIENT_ID]&redirect_uri=[REDIRECT_URI]&scope=all&domain=[DOMAIN]
        access_token_uri: https://sso-upower.agilines.com/pub/oauth2/access_token?grant_type=authorization_code&client_id=[CLIENT_ID]&app_secret=[CLIENT_SECRET]&code=[CODE]
        user_info_uri: https://sso-upower.agilines.com/cli/full_user_info?access_token=[ACCESS_TOKEN]&domain=[DOMAIN]
        logout_uri: https://sso-upower.agilines.com/cli/logout?access_token=[ACCESS_TOKEN]
  oauth2:
    default:
      enable: true
  oauth:
    config:
      no-user-redirect: https://uc-upower.agilines.com/api/v1/ithinkdt-user-center/pub/register_user?profile=[PROFILE]&redirectUri=[REDIRECT_URI]
sso:
  default:
    redirect_uri: '[HOST]/pmp/home'
  redirect_uri_expire: 10

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 10.164.9.48:26379,10.164.9.49:26379,10.164.9.50:26379
    pool:
      max-idle: 80
      max-active: 100
      max-wait: 3000
      min-idle: 0
    maxIdle: 300
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    timeout: 10000
    database: 15
    #hostName: 10.164.9.211
    password: O21$AgiLines&HF
    port: 36379
mq:
  name-server: mq-namesrv-0.mq-namesrv:9876;mq-namesrv-1.mq-namesrv:9876
  consumer:
    group: UC-SYNC-CONSUMER
    topic: uc-sync-topic
    tag: url


uc:
  app: ithinkdt-user-center