feign:
    connect:
        timeout:
            millis: 30000
    httpclient:
        enabled: true
    hystrix:
        enabled: true
    read:
        timeout:
            millis: 5000
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: SEMAPHORE
                    thread:
                        timeoutInMilliseconds: 10000.0
                timeout:
                    enabled: false
i18n:
    cookie:
        maxage: 31536000
        name: locale
    default:
        locale: zh_CN
mybatis-plus:
    config-location: classpath:conf/dao/sql-map-config.xml
    mapper-locations: classpath:/mapper/*.xml,classpath*:/conf/dao/sqlmap/*.xml
    type-aliases-package: com.ithinkdt.web.portal.entity.*.*
ribbon:
    ConnectTimeout: 30000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ReadTimeout: 5000
server:
    port: 8080
spring:
    redis:
        maxIdle: 300
        maxTotal: 1000
        maxWaitMillis: 1000
        minEvictableIdleTimeMillis: 300000
        numTestsPerEvictionRun: 1024
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 30000
        timeout: 10000
        database: 15
        sentinel:
            master: mymaster
            nodes: 10.164.9.48:26379,10.164.9.49:26379,10.164.9.50:26379
        password: O21$AgiLines&HF
        port: 36379
    application:
        name: ithinkdt-user-center
    auth:
        clientId: client_1
        secret: 123456
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,slf4j
        initialSize: 1
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        validationQuery: SELECT 'x'
        password: O21$AgiLines%HF
        username: root
        url: jdbc:mysql://10.164.9.99:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    freemarker:
        cache: false
        suffix: .html
        content-type: text/html
        enabled: true
        template-loader-path: classpath:/templates/
        charset: UTF-8
    mvc:
        throw-exception-if-no-handler-found: true
    profiles:
        active: dev
logging:
    level:
        springfox:
            documentation:
                spring: ERROR
app-mq:
    broker: mq-namesrv-0.mq-namesrv:9876;mq-namesrv-1.mq-namesrv:9876
    consumerGroup: srm-dev
    producerGroup: srm-dev
    topic:
    tag: "*"
    tenantTopic: UC-TENANT
    tenantEndDateTag: EndDate
    tenantAppEndTag: EndAppDate
ithinkdt:
    app:
        name: user-center
    security:
        defaultPassword: 123456
        token_holder_on: true
        social:
              - icon: wechat.png
                icon_alive: alive-wechat.png
                title: 深迪SSO登录
                auth_type: Author2.0
                auth_kind: ithinkdtsso
                client_id: srm
                client_secret: 123456
                url: https://uc-upower.agilines.com/api/v1/ithinkdt-user-center/pub/ssologin/callback
                ssoUrl: https://uc-upower.agilines.com/api/v1/ithinkdt-user-center/pub/ssologin
                user-authorization-uri: https://sso-upower.agilines.com/pub/oauth2/authorize?response_type=code&client_id=srm&redirect_uri=[REDIRECT_URI]&scope=all&domain=[DOMAIN]
                access_token_uri: https://sso-upower.agilines.com/pub/oauth2/access_token?grant_type=authorization_code&client_id=srm&client_secret=123456&code=[CODE]&redirect_uri=[REDIRECT_URI]
                user_info_uri: https://sso-upower.agilines.com/cli/full_user_info?access_token=[ACCESS_TOKEN]&domain=[DOMAIN]
                logout_uri: https://sso-upower.agilines.com/cli/logout?access_token=[ACCESS_TOKEN]
    default:
        redirect_uri: https://uc-upower.agilines.com/#/init-project
    oauth:
        config:
            no-user-redirect: https://uc-upower.agilines.com/api/v1/ithinkdt-user-center/pub/register_user?profile=[PROFILE]&redirectUri=[REDIRECT_URI]
    user-center:
        config:
            register-uri: https://uc-upower.agilines.com/#/pub/register?domain=[DOMAIN]&profile=[PROFILE]&redirectUri=[REDIRECT_URI]
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: "http://eureka-0.eureka:8500/eureka/,http://eureka-1.eureka:8500/eureka/,http://eureka-2.eureka:8500/eureka/"
    instance:
        prefer-ip-address: true