server:
  port: 8080
spring:
  application:
    name: pcp-index
  data:
    neo4j:
      uri: bolt://neo4j:7687
      username: neo4j
      password: agilines
  datasource:
    #注意： MySQL连接驱动是8.0，要使用以下类作为驱动类
    driver-class-name: com.mysql.jdbc.Driver
    password: O21$AgiLines%HF
    username: root
    url: jdbc:mysql://10.164.9.99:3306/pcp_common?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-0.eureka:8500/eureka/,http://eureka-1.eureka:8500/eureka/,http://eureka-2.eureka:8500/eureka/
  instance:
    prefer-ip-address: true


es:
  urls: 10.50.80.4:9200,10.50.80.5:9200,10.50.80.6:9200
  user: elastic
  password: cXPrbct27M5usXzq
  biz:
    map: "{'Task': 'upower_prd_project_task_search', 'Issue': 'upower_prd_issue_search', 'CADPart': 'upower_prd_cadpart_search', 'epart': 'upower_prd_epart_search'}"
  log:
    indexPattern: business-log-*
    appName: biz-log-project_prd
    log-urls: 10.164.9.73:9200,10.164.9.74:9200,10.164.9.75:9200
    log-user: elastic
    log-password: iThinkDT.com

mq:
  name-server: mq-namesrv-0.mq-namesrv:9876;mq-namesrv-1.mq-namesrv:9876
  consumer:
    group: GRAPH-CONSUMER
    topic: PCP-C-GRAPH_MODEL
  log:
    group: g1
    topic: CANAL_MYSQL
logging:
  level:
    org:
      springframework:
        data:
          neo4j:
            cypher: trace

mybatis:
  type-aliases-package: com.agilines.data.index.bean
  mapper-locations: classpath*:mapper/*.xml


