    server:
      port: 9504
    spring:
      # Redis
      redis:
        maxIdle: 300
        maxTotal: 1000
        maxWaitMillis: 1000
        minEvictableIdleTimeMillis: 300000
        numTestsPerEvictionRun: 1024
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 30000
        timeout: 10000
        database: 15
        sentinel:
            master: mymaster
            nodes: 10.164.9.48:26379,10.164.9.49:26379,10.164.9.50:26379
        password: O21$AgiLines&HF
        port: 36379

      application:
        name: notification-center
      profiles:
        active: qa
      datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        minIdle: 5
        validationQuery: SELECT 'x'
        initialSize: 1
        maxWait: 60000
        poolPreparedStatements: true
        filters: stat,wall,slf4j
        type: com.alibaba.druid.pool.DruidDataSource
        maxPoolPreparedStatementPerConnectionSize: 20
        testOnBorrow: false
        testWhileIdle: true
        minEvictableIdleTimeMillis: 300000
        timeBetweenEvictionRunsMillis: 60000
        testOnReturn: false
        driver-class-name: com.mysql.cj.jdbc.Driver
        maxActive: 20
        removeAbandoned: false
        url: jdbc:mysql://10.164.9.99:3306/notification_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
        password: O21$AgiLines%HF
        username: root
      jackson:
        time-zone: GMT+8
        default-property-inclusion: non_null
    feign:
      connect:
        timeout:
          millis: 3000
      httpclient:
        enabled: true
      hystrix:
        enabled: true
      read:
        timeout:
          millis: 5000
    hystrix:
      command:
        default:
          execution:
            isolation:
              strategy: SEMAPHORE
              thread:
                timeoutInMilliseconds: 10000.0
            timeout:
                enabled: false
    ribbon:
      ConnectTimeout: 3000
      MaxAutoRetries: 1
      MaxAutoRetriesNextServer: 2
      ReadTimeout: 5000

    # Mybatis Plus
    mybatis-plus:
      config-location: classpath:conf/dao/sql-map-config.xml
      mapper-locations: classpath:mapper/*.xml,classpath*:conf/dao/sqlmap/*.xml
      type-aliases-package: com.ithinkdt.notification.center.entity

    # 国际化配置
    i18n:
      default:
        locale: zh_CN
      cookie:
        maxage: 31536000
        name: locale

    # Security
    ithinkdt:
      security:
        social:
          - icon: wechat.png
            icon_alive: alive-wechat.png
            title: 深迪SSO登录
            auth_type: Author2.0
            auth_kind: ithinkdtsso
            client_id: nc
            client_secret: 123456
            url: https://nc-upower.agilines.com/api/v1/notification-center/pub/ssologin/callback
            user-authorization-uri: https://sso-upower.agilines.com/pub/oauth2/authorize?response_type=code&client_id=nc&redirect_uri=[REDIRECT_URI]&scope=all
            access_token_uri: https://sso-upower.agilines.com/pub/oauth2/access_token?grant_type=authorization_code&client_id=nc&client_secret=123456&code=[CODE]&redirect_uri=[REDIRECT_URI]
            user_info_uri: https://sso-upower.agilines.com/cli/full_user_info?access_token=[ACCESS_TOKEN]&domain=[DOMAIN]
            logout_uri: https://sso-upower.agilines.com/cli/logout?access_token=[ACCESS_TOKEN]
      oauth2:
        default:
          enable: true

    # Spring Cloud
    eureka:
      client:
        service-url:
          defaultZone: "http://eureka-0.eureka:8500/eureka/,http://eureka-1.eureka:8500/eureka/,http://eureka-2.eureka:8500/eureka/"
        fetch-registry: true
        register-with-eureka: true
      instance:
        prefer-ip-address: true

    # MQ
    mq:
      broker: mq-namesrv-0.mq-namesrv:9876;mq-namesrv-1.mq-namesrv:9876
      consumerGroup: notification-center-consumer
      producerGroup: notification-center-producer
      controlConsumerGroup: notification-center-control
      topic: nc-sync-topic
      tag: "*"