hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000.0
        timeout:
          enabled: false
i18n:
  cookie:
    maxage: 31536000
    name: locale
  default:
    locale: zh_CN
mybatis-plus:
  config-location: classpath:conf/dao/sql-map-config.xml
  mapper-locations: classpath*:conf/dao/sqlmap/*.xml,classpath*:mapper/*.xml
  type-aliases-package: com.ithinkdt.web.entity
  #自定义类型处理器的包名
  type-handlers-package: com.ithinkdt.web.util;com.ithinkdt.plugin.mybatis.plugin.handler

ribbon:
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  ReadTimeout: 5000
server:
  port: 8080
spring:
  application:
    name: pcp-issue
  auth:
    clientId: client_1
    secret: 123456
  datasource:
    password: dasda32GSADfd
    username: root
    url: jdbc:mysql://10.164.9.234:3306/pcp_issue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,slf4j
    initialSize: 1
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: SELECT 'x'
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: prd


CodePre:
  PO

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-0.eureka:8080/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    dao:
      com:
        ithinkdt: INFO
    com:
      ithinkdt: INFO
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
    org:
      springframework: INFO
redis:
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
  testOnBorrow: true
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 30000
  timeout: 10000
  database: 15
  hostName: 10.164.9.234
  password: dadas1ASAc3
  port: 26379

ithinkdt:
  app:
    name: pcp-issue
  security:
    social:
      - icon: wechat.png
        icon_alive: alive-wechat.png
        title: 深迪SSO登录
        auth_type: Author2.0
        auth_kind: ithinkdtsso
        client_id: pcp
        client_secret: 123456
        url: 'http://pcp-uat.agilines.com/api/v1/pcp-issue/pub/ssologin/callback'
        ssoUrl: 'http://pcp-uat.agilines.com/api/v1/pcp-issue/pub/ssologin'
        user-authorization-uri: http://sso-uat.agilines.com/pub/oauth2/authorize?response_type=code&client_id=[CLIENT_ID]&redirect_uri=[REDIRECT_URI]&scope=all&domain=[DOMAIN]
        access_token_uri: http://sso-uat.agilines.com/pub/oauth2/access_token?grant_type=authorization_code&client_id=[CLIENT_ID]&app_secret=[CLIENT_SECRET]&code=[CODE]
        user_info_uri: http://sso-uat.agilines.com/cli/full_user_info?access_token=[ACCESS_TOKEN]&domain=[DOMAIN]
        logout_uri: http://sso-uat.agilines.com/cli/logout?access_token=[ACCESS_TOKEN]
  oauth2:
    default:
      enable: true
  oauth:
    config:
      no-user-redirect: http://uc-uat.agilines.com/api/v1/ithinkdt-user-center/pub/register_user?profile=[PROFILE]&redirectUri=[REDIRECT_URI]


mq:
  broker: mq-namesrv-0.mq-namesrv:9876
  producerGroup: PCP-SPX
  topic: mail-topic
  tag: "*"

  producer:
    topic:
      issue: PCP-SPX-ISSUE
      graph: PCP-P-GRAPH_MODEL

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
task:
  issue:
    proc:
      id: issue_process
feishu:
  issue:
    isWorking: false

dingTalk:
  issue:
    isWorking: false